Feature/holidays
enroot-mumbai/mynafe pull request #20
Opened 2023-08-12 22:00 UTC by yashnerkar

2023-08-14 19:17 UTC, Mehul2410 requested changes

2023-08-14 19:17 UTC, Mehul2410 commented on pages/staff/login/index.tsx
> +  //   const hiddenFeature = process.env.HIDDEN_FEATURE;
remove comments

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/Admin/AppointmentTracker/AppointmentCard.tsx
> +// import { updateAttendanceOfUser } from "../../utils/api/appointment";
remove comment

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/Admin/AppointmentTracker/AppointmentCard.tsx
> +              target="_blank"
remove

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/Admin/CasePaperTracker/index.tsx
remove empty file

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/Admin/PrescriptionTracker/PrescriptionCard.tsx
> +  const style = {
next time create a folder and add these styles there

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/DashboardCards/index.tsx
> +        style={{
use csss here

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/DownloadComponent/index.tsx
> +      {/* <h3>Downloads</h3> */}
remove

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/Prescription/PrescriptionTable.tsx
> +  // { id: "id", label: "Id", minWidth: 50 },
remove comments

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/Prescription/index.tsx
> +  //   const pdf = new jsPDF("portrait", "pt", "a4");
remove

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/holiday/HolidayModal.tsx
pls create a reusable component i feel the code is repeated

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/layout/Navigation.tsx
> +      </div>{" "}
remove double quotes

2023-08-14 19:17 UTC, Mehul2410 commented on src/components/logout/Logout.tsx
>  import mixpanel from "mixpanel-browser";
remove

2023-08-14 19:17 UTC, Mehul2410 commented on src/features/telehealth/TelehealthTabs.tsx
remove it

2023-08-14 19:17 UTC, Mehul2410 commented on src/theme/global.scss
> +$med: 768px;
what is this?

2023-08-14 19:17 UTC, Mehul2410 commented on src/theme/global.scss
> +// max-width: 768px;
remove

2023-08-14 19:17 UTC, Mehul2410 commented on src/theme/global.scss
> +    //do Smth
what is this?

2023-08-14 19:17 UTC, Mehul2410 commented on src/utils/api/index.tsx
remove unnecessary comments

2023-08-14 19:21 UTC, yashnerkar commented on pages/admin/chats/index.tsx
> +          .from("distinct_private_chats4")
Its a 4

2023-08-14 19:53 UTC, yashnerkar commented on pages/admin/chats/private-chat/[id].tsx
>            .insert([
okay! I will keep in mind.
removed comment

2023-08-14 19:55 UTC, yashnerkar commented on pages/admin/chats/index.tsx
> +    // if (token) {
removed comment

2023-08-14 19:55 UTC, yashnerkar commented on pages/admin/chats/index.tsx
> +            {/* single object */}
removed the comment

2023-08-14 20:07 UTC, yashnerkar commented on pages/admin/chats/index.tsx
>  const receiverAdminPhone = "9594702015";
added to the env

2023-08-14 20:13 UTC, yashnerkar commented on pages/admin/doctor/registration/RegisterModal.tsx
> +import Box from "@mui/material/Box";
sure! will implement this from now

2023-08-14 20:13 UTC, yashnerkar commented on pages/admin/doctor/registration/RegisterModal.tsx
> +// Import the updated RegisterDoctor component
removed the comment

2023-08-14 20:17 UTC, yashnerkar commented on pages/admin/holidays/AllHolidays.tsx
> +// import DownloadsComponent from "../../components/DownloadComponent";
removed the comment

2023-08-14 20:17 UTC, yashnerkar commented on pages/admin/holidays/index.tsx
> +  // const { token } = React.useContext(UserPropsContext);
removed the comment

2023-08-14 20:18 UTC, yashnerkar commented on pages/admin/holidays/index.tsx
> +    console.log(result);
removed logs

2023-08-14 20:18 UTC, yashnerkar commented on pages/admin/users.tsx
> +  useEffect(() => {
added new line

2023-08-14 20:18 UTC, yashnerkar commented on pages/admin/users/[userToken].tsx
> +
removed new line

2023-08-14 20:19 UTC, yashnerkar commented on pages/admin/videoProgress/index.tsx
> +    // const data: any = [];
removed the comment

2023-08-14 20:21 UTC, yashnerkar commented on pages/doctor/alldoctors/index.tsx
> +  const fetchAllDoctors = async () => {
added new line

2023-08-14 20:24 UTC, yashnerkar commented on pages/doctor/holidays/AllHolidays.tsx
> +// import DownloadsComponent from "../../components/DownloadComponent";
removed

2023-08-14 20:24 UTC, yashnerkar commented on pages/doctor/holidays/index.tsx
> +  // const { token } = React.useContext(UserPropsContext);
removed comment

2023-08-14 20:37 UTC, yashnerkar commented on pages/doctor/holidays/index.tsx
> +  useEffect(() => {
added new line.
The componet UI is slightly different than other.  Try to refactor it

2023-08-14 20:38 UTC, yashnerkar commented on pages/doctor/telehealth/DoctorBookings.tsx
> +// import SwapSlotModal from "./SwapSlots";
removed comments

2023-08-14 20:39 UTC, yashnerkar commented on pages/doctor/telehealth/DoctorBookings.tsx
removed the unused code

2023-08-14 20:40 UTC, yashnerkar commented on pages/doctor/telehealth/MedicineSelector.tsx
> +  console.log(doctorAvailability);
remove the logs

2023-08-14 20:41 UTC, yashnerkar commented on pages/doctor/telehealth/ShowPrescriptionModal.tsx
> +          {/* {Object.keys(prescriptionData).map(
removed the unused code

2023-08-14 20:41 UTC, yashnerkar commented on pages/doctor/users/Users.tsx
>  // import DownloadsComponent from "../../DownloadComponent";
removed the comments

2023-08-14 20:43 UTC, yashnerkar commented on pages/doctor/users/index.tsx
> +    <div className="">
removed classname

2023-08-14 20:45 UTC, yashnerkar commented on pages/profile/edit.tsx
> +      delete data.otherProgram;
actually remaining keys are not part of the tracking variables that's why I didnt make it in one object

2023-08-14 20:45 UTC, yashnerkar commented on pages/staff/login/index.tsx
> +  //   const hiddenFeature = process.env.HIDDEN_FEATURE;
removed the comments

2023-08-14 20:46 UTC, yashnerkar commented on src/components/Admin/AppointmentTracker/AppointmentCard.tsx
> +// import { updateAttendanceOfUser } from "../../utils/api/appointment";
remvoed the comment

2023-08-14 20:48 UTC, yashnerkar commented on src/components/Admin/AppointmentTracker/AppointmentCard.tsx
> +              target="_blank"
I have kept it for future reference. So not removing for now

2023-08-14 20:48 UTC, yashnerkar commented on src/components/Admin/CasePaperTracker/index.tsx
removed

2023-08-14 20:56 UTC, yashnerkar commented on src/components/Admin/PrescriptionTracker/PrescriptionCard.tsx
> +  const style = {
this are actually the modal default styles that's why I have kept there!

2023-08-14 21:08 UTC, yashnerkar commented on src/components/DownloadComponent/index.tsx
> +      {/* <h3>Downloads</h3> */}
removed

2023-08-14 21:11 UTC, yashnerkar commented on src/components/Prescription/PrescriptionTable.tsx
> +  // { id: "id", label: "Id", minWidth: 50 },
removed the comments

2023-08-14 21:12 UTC, yashnerkar commented on src/components/Prescription/PrescriptionTable.tsx
> +  // { id: "id", label: "Id", minWidth: 50 },
removed the comments

2023-08-14 21:15 UTC, yashnerkar commented on src/components/Prescription/index.tsx
> +  //   const pdf = new jsPDF("portrait", "pt", "a4");
removed the comments

2023-08-14 21:18 UTC, yashnerkar commented on src/components/holiday/HolidayModal.tsx
I have used this component in AllHoliday component in the doctor section as well as in admin section. used a single component in both the cases

2023-08-14 21:18 UTC, yashnerkar commented on src/components/logout/Logout.tsx
>  import mixpanel from "mixpanel-browser";
removed the comments

2023-08-14 21:21 UTC, yashnerkar commented on src/theme/global.scss
> +    //do Smth
resolved,added responsive of the navigationbar

2023-08-14 21:22 UTC, yashnerkar commented on src/theme/global.scss
> +$med: 768px;
removed the unused variable $md=768

2023-08-14 21:22 UTC, yashnerkar commented on src/utils/api/index.tsx
removed the comments

2023-08-14 21:23 UTC, yashnerkar commented on src/theme/global.scss
> +// max-width: 768px;
resolved

2023-08-14 21:24 UTC, yashnerkar commented on pages/admin/holidays/index.tsx
> +  useEffect(() => {
added new line

2023-08-14 21:25 UTC, yashnerkar commented on pages/admin/holidays/index.tsx
> +  console.log(holidays);
removed console log

2023-08-14 21:26 UTC, yashnerkar commented on pages/chats/myna.tsx
> +              receiverName: "Myna Expert",
changed the receiver number to env in all files

2023-08-14 21:27 UTC, yashnerkar commented on pages/chats/myna.tsx
> +              receiverName: "Myna Expert",
changed the receiver number to env in all files

2023-08-14 21:28 UTC, yashnerkar commented on src/components/DashboardCards/index.tsx
> +        style={{
added css

2023-09-04 11:42 UTC, enroot-mumbai approved these changes

2023-09-04 14:19 UTC, merged